version: '3.8'

services:
  db-alquileres:
    image: postgres:15-alpine
    container_name: servidor-postgres-alquileres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: alquileres_ica_db
    ports:
      - "5432:5432"
    volumes:
      - alquileres_data:/var/lib/postgresql/data

volumes:
  alquileres_data: