spring.application.name=sistema-alquileres
server.port=9085
server.servlet.context-path=/apialquiler

# Database Configuration (Example for PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/alquileres_ica_db?stringtype=unspecified
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#Depuracion
spring.jpa.show-sql=true
#JSON Configuration
#spring.jackson.default-property-inclusion=non_null